@extends('layouts.layout')

@section('content')
    @php
        $pageSettings = $pageSettings ?? [];
    @endphp
    <section class="content-header pb-0 no-print">
        <div class="container-fluid">
            <div class="row align-items-center mb-3">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark font-weight-bold">@lang('Patient History')</h1>
                    <p class="text-muted mb-0">@lang('View and manage comprehensive patient records')</p>
                </div>
                <div class="col-sm-6 text-right">
                    <div id="buttonContainer" class="d-inline-flex align-items-center">

                        <input type="hidden" id="record_id" value="{{ $patientDetail->id }}">
                        <input type="hidden" id="table_name" value="patient">

                        <!-- Actions generated by JS based on tab -->
                        <div id="medicalHistoryButtons" class="history-action-btn mr-2">
                            @if ($patientMedicalHistories->isEmpty())
                                <a href="{{ route('patient-medical-histories.create.from-patient', ['userid' => $patientDetail->id]) }}"
                                    class="btn btn-primary shadow-sm">
                                    <i class="fas fa-plus-circle mr-1"></i> @lang('Add Medical')
                                </a>
                            @endif
                        </div>

                        <div id="drugHistoryButtons" class="history-action-btn mr-2" style="display: none;">
                            @if ($patientDrugHistories->isEmpty())
                                <a href="{{ route('patient-drug-histories.create.from-patient', ['userid' => $patientDetail->id]) }}"
                                    class="btn btn-primary shadow-sm">
                                    <i class="fas fa-plus-circle mr-1"></i> @lang('Add Drug')
                                </a>
                            @endif
                        </div>

                        <div id="socialHistoryButtons" class="history-action-btn mr-2" style="display: none;">
                            @if ($patientSocialHistories->isEmpty())
                                <a href="{{ route('patient-social-histories.create.from-patient', ['userid' => $patientDetail->id]) }}"
                                    class="btn btn-primary shadow-sm">
                                    <i class="fas fa-plus-circle mr-1"></i> @lang('Add Social')
                                </a>
                            @endif
                        </div>

                        <div id="dentalHistoryButtons" class="history-action-btn mr-2" style="display: none;">
                            @if ($patientDentalHistories->isEmpty())
                                <a href="{{ route('patient-dental-histories.create.from-patient', ['userid' => $patientDetail->id]) }}"
                                    class="btn btn-primary shadow-sm">
                                    <i class="fas fa-plus-circle mr-1"></i> @lang('Add Dental')
                                </a>
                            @endif
                        </div>

                        <a href="{{ route('patient-details.index') }}"
                            class="btn btn-light border shadow-sm text-muted mr-2">
                            <i class="fas fa-arrow-left mr-1"></i> @lang('Back')
                        </a>

                        <button class="btn btn-outline-secondary shadow-sm mr-1 no-print" type="button"
                            data-toggle="collapse" data-target="#printSettings" aria-expanded="false">
                            <i class="fas fa-cog"></i> @lang('Settings')
                        </button>
                        <button id="doPrint" class="btn btn-secondary shadow-sm no-print">
                            <i class="fas fa-print mr-2"></i> @lang('Print')
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="content mt-3">
        <div class="container-fluid">

            <!-- Print Settings Panel -->
            <div class="row no-print">
                <div class="col-12">
                    <div class="collapse mb-3 border rounded p-4 bg-light shadow-sm" id="printSettings">
                        <div class="d-flex align-items-center mb-4">
                            <i class="fas fa-sliders-h text-primary mr-2"></i>
                            <h5 class="mb-0 font-weight-bold">@lang('Customize Print Layout')</h5>
                        </div>
                        <div class="row align-items-end">
                            <div class="col-md-2">
                                <div class="form-group mb-0">
                                    <label class="small text-muted font-weight-bold mb-2 d-block">@lang('HEADER')</label>
                                    <div class="custom-control custom-switch custom-switch-lg">
                                        <input type="checkbox" class="custom-control-input" id="showHeader"
                                            {{ $pageSettings['show_header'] ?? true ? 'checked' : '' }}>
                                        <label class="custom-control-label font-weight-normal"
                                            for="showHeader">@lang('Show')</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group mb-0">
                                    <label class="small text-muted font-weight-bold mb-2 d-block">@lang('FONT SIZE (PX)')</label>
                                    <div class="input-group input-group-sm">
                                        <input type="number" id="fontSize" class="form-control"
                                            value="{{ $pageSettings['font_size'] ?? 14 }}" placeholder="14">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group mb-0">
                                    <label class="small text-muted font-weight-bold mb-2 d-block">@lang('TOP MARGIN (MM)')</label>
                                    <input type="number" id="marginTop" class="form-control"
                                        value="{{ $pageSettings['margin_top'] ?? 0 }}" placeholder="0">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group mb-0">
                                    <label class="small text-muted font-weight-bold mb-2 d-block">@lang('LEFT MARGIN (MM)')</label>
                                    <input type="number" id="marginLeft" class="form-control"
                                        value="{{ $pageSettings['margin_left'] ?? 0 }}" placeholder="0">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-primary btn-sm btn-block shadow-sm" id="saveSettings">
                                    <i class="fas fa-save mr-1"></i> @lang('Save')
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Patient Info Card -->
            <div class="card shadow-sm border-0 mb-4 overflow-hidden" style="border-radius: 12px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="d-flex align-items-center">
                            <div class="position-relative mr-4">
                                @if ($profilePicture)
                                    <img class="img-fluid rounded-circle shadow-sm"
                                        src="{{ asset('storage/' . $profilePicture) }}" alt="Profile"
                                        style="width: 80px; height: 80px; object-fit: cover; border: 3px solid #fff;" />
                                @else
                                    <div class="rounded-circle bg-light d-flex align-items-center justify-content-center border"
                                        style="width: 80px; height: 80px; border: 3px solid #fff;">
                                        <i class="fas fa-user fa-2x text-secondary"></i>
                                    </div>
                                @endif
                            </div>
                            <div>
                                <h2 class="font-weight-bold text-dark mb-1">{{ $patientDetail->name }}</h2>
                                <div class="d-flex align-items-center text-muted">
                                    <span class="badge badge-light border mr-2 p-2">MRN:
                                        {{ $patientDetail->patientDetails->mrn_number ?? '-' }}</span>
                                    <span class="mr-3"><i class="fas fa-phone-alt mr-1 text-primary"></i>
                                        {{ $patientDetail->phone ?: 'N/A' }}</span>
                                    <span><i class="fas fa-map-marker-alt mr-1 text-danger"></i>
                                        {{ $patientDetail->city ?: 'Unknown City' }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card shadow-sm border-0" style="border-radius: 12px; min-height: 500px;">
                        <div class="card-header bg-white p-0 border-bottom-0">
                            <ul class="nav nav-tabs nav-fill custom-tabs pt-3 px-3" id="historyTabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active py-3 font-weight-bold" id="medical-tab" data-toggle="tab"
                                        href="#medical" role="tab" aria-controls="medical" aria-selected="true">
                                        <i class="fas fa-notes-medical mr-2 text-primary"></i>@lang('Medical History')
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-3 font-weight-bold" id="drug-tab" data-toggle="tab"
                                        href="#drug" role="tab" aria-controls="drug" aria-selected="false">
                                        <i class="fas fa-pills mr-2 text-success"></i>@lang('Drug History')
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-3 font-weight-bold" id="social-tab" data-toggle="tab"
                                        href="#social" role="tab" aria-controls="social" aria-selected="false">
                                        <i class="fas fa-users mr-2 text-info"></i>@lang('Social History')
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-3 font-weight-bold" id="dental-tab" data-toggle="tab"
                                        href="#dental" role="tab" aria-controls="dental" aria-selected="false">
                                        <i class="fas fa-tooth mr-2 text-warning"></i>@lang('Dental History')
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="card-body bg-light p-4">
                            <div class="tab-content" id="historyTabContent">

                                <!-- Medical History -->
                                <div class="tab-pane fade show active" id="medical" role="tabpanel"
                                    aria-labelledby="medical-tab">
                                    @if ($patientMedicalHistories->isNotEmpty())
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <h5 class="font-weight-bold text-dark m-0">@lang('Medical Records')</h5>
                                            <a href="{{ route('patient-medical-histories.edit', ['patient_medical_history' => $patientMedicalHistories->first()->id]) }}"
                                                class="btn btn-sm btn-outline-primary">
                                                <i class="fas fa-edit mr-1"></i> @lang('Edit Details')
                                            </a>
                                        </div>
                                        <div class="row">
                                            @foreach ($patientMedicalHistories as $item)
                                                <div class="col-md-6 col-lg-4 mb-4">
                                                    <div class="card border-0 shadow-sm h-100 history-card">
                                                        <div class="card-body position-relative">
                                                            <div class="icon-bg"><i class="fas fa-notes-medical"></i>
                                                            </div>
                                                            <h6 class="text-primary font-weight-bold mb-2">
                                                                {{ $item->ddMedicalHistory->title }}</h6>
                                                            <p class="text-muted mb-0 small">
                                                                {{ $item->comments ?: 'No additional comments.' }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                        <!-- Documents Section -->
                                        <div id="medicalDocumentsCard"
                                            class="card shadow-sm border-0 mt-4 rounded-lg overflow-hidden"
                                            style="display: none;">
                                            <div class="card-header bg-white p-3 border-bottom">
                                                <h6 class="font-weight-bold m-0 text-dark"><i
                                                        class="fas fa-paperclip mr-2 text-muted"></i>@lang('Attached Documents')
                                                </h6>
                                            </div>
                                            <div class="card-body p-0">
                                                <div class="table-responsive">
                                                    <table class="table table-hover mb-0">
                                                        <thead class="bg-light text-muted small text-uppercase">
                                                            <tr>
                                                                <th class="border-0 pl-4">@lang('File Name')</th>
                                                                <th class="border-0">@lang('Uploaded By')</th>
                                                                <th class="border-0">@lang('Date')</th>
                                                                <th class="border-0 text-right pr-4">@lang('Actions')
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="medicalHistoryTableBody" class="fileTableBody"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    @else
                                        <div class="text-center py-5">
                                            <div class="mb-3">
                                                <i class="fas fa-notes-medical fa-4x text-muted opacity-25"></i>
                                            </div>
                                            <h5 class="text-muted">@lang('No medical history recorded')</h5>
                                            <p class="text-muted small">@lang('Click "Add Medical" above to create a new record.')</p>
                                        </div>
                                    @endif
                                </div>

                                <!-- Drug History -->
                                <div class="tab-pane fade" id="drug" role="tabpanel" aria-labelledby="drug-tab">
                                    @if ($patientDrugHistories->isNotEmpty())
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <h5 class="font-weight-bold text-dark m-0">@lang('Drug Records')</h5>
                                            <a href="{{ route('patient-drug-histories.edit', ['patient_drug_history' => $patientDrugHistories->first()->id]) }}"
                                                class="btn btn-sm btn-outline-primary">
                                                <i class="fas fa-edit mr-1"></i> @lang('Edit Details')
                                            </a>
                                        </div>
                                        <div class="row">
                                            @foreach ($patientDrugHistories as $item)
                                                <div class="col-md-6 col-lg-4 mb-4">
                                                    <div class="card border-0 shadow-sm h-100 history-card">
                                                        <div class="card-body position-relative">
                                                            <div class="icon-bg"><i class="fas fa-pills"></i></div>
                                                            <h6 class="text-success font-weight-bold mb-2">
                                                                {{ $item->ddDrugHistory->title }}</h6>
                                                            <p class="text-muted mb-0 small">
                                                                {{ $item->comments ?: 'No additional comments.' }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                        <!-- Documents Section -->
                                        <div id="drugHistoryCard"
                                            class="card shadow-sm border-0 mt-4 rounded-lg overflow-hidden"
                                            style="display: none;">
                                            <div class="card-header bg-white p-3 border-bottom">
                                                <h6 class="font-weight-bold m-0 text-dark"><i
                                                        class="fas fa-paperclip mr-2 text-muted"></i>@lang('Attached Documents')
                                                </h6>
                                            </div>
                                            <div class="card-body p-0">
                                                <div class="table-responsive">
                                                    <table class="table table-hover mb-0">
                                                        <thead class="bg-light text-muted small text-uppercase">
                                                            <tr>
                                                                <th class="border-0 pl-4">@lang('File Name')</th>
                                                                <th class="border-0">@lang('Uploaded By')</th>
                                                                <th class="border-0">@lang('Date')</th>
                                                                <th class="border-0 text-right pr-4">@lang('Actions')
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="drugHistoryTableBody" class="fileTableBody"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    @else
                                        <div class="text-center py-5">
                                            <div class="mb-3">
                                                <i class="fas fa-pills fa-4x text-muted opacity-25"></i>
                                            </div>
                                            <h5 class="text-muted">@lang('No drug history recorded')</h5>
                                        </div>
                                    @endif
                                </div>

                                <!-- Social History -->
                                <div class="tab-pane fade" id="social" role="tabpanel" aria-labelledby="social-tab">
                                    @if ($patientSocialHistories->isNotEmpty())
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <h5 class="font-weight-bold text-dark m-0">@lang('Social Records')</h5>
                                            <a href="{{ route('patient-social-histories.edit', ['patient_social_history' => $patientSocialHistories->first()->id]) }}"
                                                class="btn btn-sm btn-outline-primary">
                                                <i class="fas fa-edit mr-1"></i> @lang('Edit Details')
                                            </a>
                                        </div>
                                        <div class="row">
                                            @foreach ($patientSocialHistories as $item)
                                                <div class="col-md-6 col-lg-4 mb-4">
                                                    <div class="card border-0 shadow-sm h-100 history-card">
                                                        <div class="card-body position-relative">
                                                            <div class="icon-bg"><i class="fas fa-users"></i></div>
                                                            <h6 class="text-info font-weight-bold mb-2">
                                                                {{ $item->ddSocialHistory->title }}</h6>
                                                            <p class="text-muted mb-0 small">
                                                                {{ $item->comments ?: 'No additional comments.' }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                        <!-- Documents Section -->
                                        <div id="socialHistoryCard"
                                            class="card shadow-sm border-0 mt-4 rounded-lg overflow-hidden"
                                            style="display: none;">
                                            <div class="card-header bg-white p-3 border-bottom">
                                                <h6 class="font-weight-bold m-0 text-dark"><i
                                                        class="fas fa-paperclip mr-2 text-muted"></i>@lang('Attached Documents')
                                                </h6>
                                            </div>
                                            <div class="card-body p-0">
                                                <div class="table-responsive">
                                                    <table class="table table-hover mb-0">
                                                        <thead class="bg-light text-muted small text-uppercase">
                                                            <tr>
                                                                <th class="border-0 pl-4">@lang('File Name')</th>
                                                                <th class="border-0">@lang('Uploaded By')</th>
                                                                <th class="border-0">@lang('Date')</th>
                                                                <th class="border-0 text-right pr-4">@lang('Actions')
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="socialHistoryTableBody" class="fileTableBody"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    @else
                                        <div class="text-center py-5">
                                            <div class="mb-3">
                                                <i class="fas fa-users fa-4x text-muted opacity-25"></i>
                                            </div>
                                            <h5 class="text-muted">@lang('No social history recorded')</h5>
                                        </div>
                                    @endif
                                </div>

                                <!-- Dental History -->
                                <div class="tab-pane fade" id="dental" role="tabpanel" aria-labelledby="dental-tab">
                                    @if ($patientDentalHistories->isNotEmpty())
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <h5 class="font-weight-bold text-dark m-0">@lang('Dental Records')</h5>
                                            <a href="{{ route('patient-dental-histories.edit', ['patient_dental_history' => $patientDentalHistories->first()->id]) }}"
                                                class="btn btn-sm btn-outline-primary">
                                                <i class="fas fa-edit mr-1"></i> @lang('Edit Details')
                                            </a>
                                        </div>
                                        <div class="row">
                                            @foreach ($patientDentalHistories as $item)
                                                <div class="col-md-6 col-lg-4 mb-4">
                                                    <div class="card border-0 shadow-sm h-100 history-card">
                                                        <div class="card-body position-relative">
                                                            <div class="icon-bg"><i class="fas fa-tooth"></i></div>
                                                            <h6 class="text-warning font-weight-bold mb-2">
                                                                {{ $item->ddDentalHistory->title }}</h6>
                                                            <p class="text-muted mb-0 small">
                                                                {{ $item->comments ?: 'No additional comments.' }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                        <!-- Documents Section -->
                                        <div id="dentalHistoryCard"
                                            class="card shadow-sm border-0 mt-4 rounded-lg overflow-hidden"
                                            style="display: none;">
                                            <div class="card-header bg-white p-3 border-bottom">
                                                <h6 class="font-weight-bold m-0 text-dark"><i
                                                        class="fas fa-paperclip mr-2 text-muted"></i>@lang('Attached Documents')
                                                </h6>
                                            </div>
                                            <div class="card-body p-0">
                                                <div class="table-responsive">
                                                    <table class="table table-hover mb-0">
                                                        <thead class="bg-light text-muted small text-uppercase">
                                                            <tr>
                                                                <th class="border-0 pl-4">@lang('File Name')</th>
                                                                <th class="border-0">@lang('Uploaded By')</th>
                                                                <th class="border-0">@lang('Date')</th>
                                                                <th class="border-0 text-right pr-4">@lang('Actions')
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="dentalHistoryTableBody" class="fileTableBody"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    @else
                                        <div class="text-center py-5">
                                            <div class="mb-3">
                                                <i class="fas fa-tooth fa-4x text-muted opacity-25"></i>
                                            </div>
                                            <h5 class="text-muted">@lang('No dental history recorded')</h5>
                                        </div>
                                    @endif
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="print-only-wrapper">
        @php
            $showHeader = isset($pageSettings['show_header'])
                ? $pageSettings['show_header'] === true ||
                    $pageSettings['show_header'] === 'true' ||
                    $pageSettings['show_header'] === 1 ||
                    $pageSettings['show_header'] === '1'
                : true;
            $marginTop = $pageSettings['margin_top'] ?? 0;
            $marginLeft = $pageSettings['margin_left'] ?? 0;
            $fontSize = $pageSettings['font_size'] ?? 14;
        @endphp
        <div id="print-area" style="font-size: {{ $fontSize }}px;">
            <div class="history-print-container" id="prescription-container"
                style="padding-top: {{ $marginTop }}mm; padding-left: {{ $marginLeft }}mm;">
                <div id="companyInfoBox" class="clinic-header {{ $showHeader ? '' : 'd-none' }}">
                    <div class="clinic-logo-box">
                        @if (isset($ApplicationSetting->logo) && !empty($ApplicationSetting->logo))
                            <img src="{{ asset('public/' . $ApplicationSetting->logo) }}" alt="Logo"
                                class="clinic-logo">
                        @else
                            <div class="p-3 bg-light rounded text-center"
                                style="width: 80px; height: 80px; border: 2px dashed #ccc;">
                                <i class="fas fa-hospital fa-2x text-muted mt-2"></i>
                            </div>
                        @endif
                    </div>
                    <div class="clinic-info">
                        <h4>{{ $ApplicationSetting->item_name ?? 'Company Name' }}</h4>
                        <p>{{ $ApplicationSetting->company_address ?? '' }}</p>
                        <p>{{ $ApplicationSetting->contact ?? '' }}</p>
                        <p>{{ $ApplicationSetting->company_email ?? '' }}</p>
                    </div>
                </div>

                <table class="info-table">
                    <tr>
                        <td><strong>@lang('Patient Name'):</strong> {{ $patientDetail->name }}</td>
                        <td><strong>@lang('MRN Number'):</strong> {{ $patientDetail->patientDetails->mrn_number ?? '-' }}
                        </td>
                        <td><strong>@lang('Age'):</strong>
                            {{ $patientDetail->dob ? \Carbon\Carbon::parse($patientDetail->dob)->age . ' Years' : $patientDetail->age ?? '-' }}
                        </td>
                    </tr>
                    <tr>
                        <td><strong>@lang('Phone'):</strong> {{ $patientDetail->phone ?? '-' }}</td>
                        <td><strong>@lang('Gender'):</strong> {{ $patientDetail->gender ?? '-' }}</td>
                        <td><strong>@lang('Date'):</strong> {{ date($companySettings->date_format ?? 'Y-m-d') }}</td>
                    </tr>
                </table>

                @php
                    $histories = [
                        [
                            'title' => __('Medical History'),
                            'data' => $patientMedicalHistories,
                            'key' => 'ddMedicalHistory',
                            'icon' => 'notes-medical',
                        ],
                        [
                            'title' => __('Drug History'),
                            'data' => $patientDrugHistories,
                            'key' => 'ddDrugHistory',
                            'icon' => 'pills',
                        ],
                        [
                            'title' => __('Social History'),
                            'data' => $patientSocialHistories,
                            'key' => 'ddSocialHistory',
                            'icon' => 'users',
                        ],
                        [
                            'title' => __('Dental History'),
                            'data' => $patientDentalHistories,
                            'key' => 'ddDentalHistory',
                            'icon' => 'tooth',
                        ],
                    ];
                @endphp

                @foreach ($histories as $history)
                    @if ($history['data']->isNotEmpty())
                        <div class="mb-4 history-section">
                            <h5 class="history-title mb-3"><i
                                    class="fas fa-{{ $history['icon'] }} mr-2"></i>{{ $history['title'] }}</h5>
                            <table class="table table-bordered table-sm">
                                <thead>
                                    <tr>
                                        <th style="width: 40%;">@lang('Title')</th>
                                        <th>@lang('Details')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($history['data'] as $item)
                                        <tr>
                                            <td class="font-weight-bold">{{ $item->{$history['key']}->title }}</td>
                                            <td>{{ $item->comments ?: '-' }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                @endforeach

                <div class="signature-box">
                    <div class="signature-line">
                        <strong>@lang('Signature')</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <style>
        /* 1. Hide the print wrapper on the screen */
        .print-only-wrapper {
            display: none;
        }

        /* Custom Styling for Tabs */
        .custom-tabs .nav-link {
            border: none;
            border-bottom: 3px solid transparent;
            color: #6c757d;
            transition: all 0.3s ease;
        }

        .custom-tabs .nav-link:hover {
            color: var(--primary-color);
            background: rgba(0, 0, 0, 0.02);
        }

        .custom-tabs .nav-link.active {
            color: var(--primary-color) !important;
            border-bottom-color: var(--primary-color);
            background: transparent !important;
        }

        @media print {

            /* 2. Reset Page */
            @page {
                margin: 0;
                size: auto;
            }

            body {
                background: white !important;
                color: black !important;
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
            }

            /* 3. Visibility Strategy (Most Robust) */
            body * {
                visibility: hidden;
            }

            /* 4. Force Visibility of Print Wrapper */
            .print-only-wrapper,
            .print-only-wrapper * {
                visibility: visible;
            }

            .print-only-wrapper {
                display: block !important;
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                min-height: 100vh;
                z-index: 20000;
                background-color: white !important;
            }

            /* Ensure containers are block and visible */
            #print-area,
            #prescription-container {
                display: block !important;
                width: 100% !important;
                opacity: 1 !important;
                visibility: visible !important;
            }

            #companyInfoBox {
                visibility: visible !important;
            }

            /* Font size & display handled by inline styles/classes */
        }

        #print-area * {
            font-size: {{ $pageSettings['font_size'] ?? 14 }}px !important;
        }
        }

        /* Print Layout - Prescription Style Match */
        .clinic-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 15px;
        }

        .clinic-logo-box {
            flex: 0 0 150px;
        }

        .clinic-logo {
            max-width: 100%;
            height: auto;
            max-height: 80px;
            object-fit: contain;
        }

        .clinic-info {
            text-align: right;
            flex: 1;
        }

        .clinic-info h4 {
            font-size: 26px;
            font-weight: 800;
            margin: 0 0 5px 0;
            color: #2c3e50;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .clinic-info p {
            margin: 0;
            color: #555;
            line-height: 1.4;
        }

        .info-table {
            width: 100%;
            margin-bottom: 20px;
            background-color: #f8f9fa;
            border: 1px solid #dee2e6 !important;
            border-radius: 4px;
            border-collapse: collapse;
        }

        .info-table td {
            border: 1px solid #dee2e6;
            text-align: left !important;
            padding: 8px 12px !important;
            font-size: 14px !important;
            width: 33.33%;
        }

        .signature-box {
            margin-top: 60px;
            text-align: right;
            padding-right: 30px;
        }

        .signature-line {
            border-top: 1px solid #000;
            width: 220px;
            display: inline-block;
            padding-top: 5px;
            text-align: center;
            font-weight: bold;
        }
    </style>

    <!-- JavaScript Section -->
    <script>
        var getFilesUrl = "{{ route('get-files', $patientDetail->id) }}";
        var uploadFilesUrl = "{{ route('upload-file') }}";
        var deleteFilesUrl = "{{ route('delete-file') }}";
        var baseUrl = "{{ asset('') }}";

        $(document).ready(function() {
            // Initial button state - Click the active tab to trigger button logic
            // If a hash is present, click that tab
            var hash = location.hash.replace(/^#/, ''); // ^ means starting, meaning only match # at start
            if (hash) {
                $('#historyTabs a[href="#' + hash + '"]').tab('show');
            } else {
                $('#historyTabs a.active').tab('show');
            }

            // Show/hide action buttons and document sections based on selected tab
            // Note: Renamed IDs: home->medical, profile->drug, messages->social, settings->dental
            $('#historyTabs a').on('shown.bs.tab', function(e) {
                var activeTab = $(e.target).attr('id'); // Get ID of the tab link
                $('.history-action-btn').hide();

                switch (activeTab) {
                    case 'medical-tab':
                        $('#medicalHistoryButtons').fadeIn();
                        break;
                    case 'drug-tab':
                        $('#drugHistoryButtons').fadeIn();
                        break;
                    case 'social-tab':
                        $('#socialHistoryButtons').fadeIn();
                        break;
                    case 'dental-tab':
                        $('#dentalHistoryButtons').fadeIn();
                        break;
                }
            });

            // Trigger manually for first load
            var initialTab = $('#historyTabs a.active').attr('id');
            if (initialTab) {
                $('#historyTabs a.active').trigger('shown.bs.tab');
            }

            // Print & Settings Logic
            $('#doPrint').on('click', function(e) {
                e.preventDefault();
                window.print();
            });

            $('#showHeader').change(function() {
                $('#companyInfoBox').toggleClass('d-none', !$(this).is(':checked'));
            });

            $('#marginTop').on('input change', function() {
                var val = $(this).val() || 0;
                $('#prescription-container').css('padding-top', val + 'mm'); // Using padding-top for layout
            });

            $('#marginLeft').on('input change', function() {
                var val = $(this).val() || 0;
                $('#prescription-container').css('padding-left', val + 'mm');
            });

            $('#fontSize').on('input change', function() {
                var val = $(this).val() || 14;
                $('#print-area *').css('font-size', val + 'px');
            });

            $('#saveSettings').click(function() {
                var btn = $(this);
                var originalText = btn.html();
                btn.prop('disabled', true).html(
                    '<i class="fas fa-spinner fa-spin"></i> @lang('Saving...')');

                var settings = {
                    show_header: $('#showHeader').is(':checked'),
                    margin_top: $('#marginTop').val(),
                    margin_left: $('#marginLeft').val(),
                    font_size: $('#fontSize').val()
                };

                $.ajax({
                    url: "{{ route('page-settings.store') }}",
                    method: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify({
                        _token: "{{ csrf_token() }}",
                        page_name: "patient_history_print",
                        settings: settings
                    }),
                    success: function(response) {
                        btn.html('<i class="fas fa-check"></i> @lang('Saved')');
                        setTimeout(() => {
                            btn.prop('disabled', false).html(originalText);
                        }, 2000);
                    },
                    error: function(xhr) {
                        btn.prop('disabled', false).html(
                            '<i class="fas fa-exclamation-triangle"></i> @lang('Error')'
                        );
                    }
                });
            });

            // Document section logic
            // Check if there are rows in the doc tables and show card if so
            setTimeout(function() {
                const documentCheck = [{
                        table: '#medicalHistoryTableBody',
                        card: '#medicalDocumentsCard'
                    },
                    {
                        table: '#drugHistoryTableBody',
                        card: '#drugHistoryCard'
                    },
                    {
                        table: '#socialHistoryTableBody',
                        card: '#socialHistoryCard'
                    },
                    {
                        table: '#dentalHistoryTableBody',
                        card: '#dentalHistoryCard'
                    }
                ];

                documentCheck.forEach(function(item) {
                    if ($(item.table).find('tr').length > 0) {
                        $(item.card).slideDown();
                    } else {
                        $(item.card).hide();
                    }
                });
            }, 1500); // Increased timeout slightly to be safe
        });
    </script>
@endsection
