<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Artisan;

class DevController extends Controller
{
    public function index()
    {
        $projects = Config::get('all_projects', []);
        return view('dev.index', compact('projects'));
    }

    public function apiList($authKey)
    {
        if ($authKey != 'admin@jtech') {
            return response()->json(['error' => 'Invalid auth key']);
        }

        $projects = Config::get('all_projects', []);
        $formattedProjects = [];

        foreach ($projects as $key => $project) {
            // Use Prefix as key if available, otherwise fallback to existing key (though Prefix is required)
            $newKey = $project['Prefix'] ?? $key;

            // Add base_url
            $segment = $project['SEGMENT_NAME'] ?? $key;
            $project['base_url'] = str_replace(request()->segment(1)."/", '', url($segment));

            $newProject = [
                'project_name' => $key,
                'segment_name' => $project['SEGMENT_NAME'],
                'base_url' => $project['base_url'],
            ];

            $formattedProjects[$newKey] = $newProject;
        }

        return response()->json($formattedProjects);
    }

    public function store(Request $request)
    {
        $request->validate([
            'segment_name' => 'required|string|regex:/^[a-zA-Z0-9-]+$/',
            'prefix' => 'required|string',
            'database_name' => 'required|string|regex:/^[a-zA-Z0-9_]+$/',
            'db_host' => 'required|string',
            'db_username' => 'required|string',
            'db_password' => 'nullable|string',
        ]);

        $projects = Config::get('all_projects', []);

        $segment = $request->input('segment_name');

        if (isset($projects[$segment])) {
            return redirect()->back()->with('error', 'Project with this segment already exists!');
        }

        $newProject = [
            'APP_KEY' => '', // Will be generated by TenantDatabase middleware access
            'Prefix' => $request->input('prefix'),
            'SEGMENT_NAME' => $segment,
            'HOST' => $request->input('db_host'),
            'DATABASE_NAME' => $request->input('database_name'),
            'USERNAME' => $request->input('db_username'),
            'PASSWORD' => $request->input('db_password') ?? '',
        ];

        $projects[$segment] = $newProject;

        $this->saveProjectsToConfig($projects);

        // Create Database
        try {
            // DB::statement("CREATE DATABASE IF NOT EXISTS " . $request->input('database_name'));
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Error creating database: ' . $e->getMessage());
        }

        return redirect()->route('dev.index')->with('success', 'Project created successfully!');
    }

    public function update(Request $request, $key)
    {
        $projects = Config::get('all_projects', []);

        if (!isset($projects[$key])) {
            return redirect()->back()->with('error', 'Project not found!');
        }

        $request->validate([
            'prefix' => 'required|string',
            'db_host' => 'required|string',
            'database_name' => 'required|string|regex:/^[a-zA-Z0-9_]+$/',
            'db_username' => 'required|string',
            'db_password' => 'nullable|string',
        ]);

        $projects[$key]['Prefix'] = $request->input('prefix');
        $projects[$key]['DATABASE_NAME'] = $request->input('database_name');
        $projects[$key]['HOST'] = $request->input('db_host');
        $projects[$key]['USERNAME'] = $request->input('db_username');
        $projects[$key]['PASSWORD'] = $request->input('db_password') ?? '';

        $this->saveProjectsToConfig($projects);

        return redirect()->route('dev.index')->with('success', 'Project configuration updated successfully!');
    }

    public function destroy(Request $request, $key)
    {
        $projects = Config::get('all_projects', []);

        if (!isset($projects[$key])) {
            return redirect()->back()->with('error', 'Project not found!');
        }

        $dbName = $projects[$key]['DATABASE_NAME'];

        unset($projects[$key]);
        $this->saveProjectsToConfig($projects);

        if ($request->has('drop_database') && $request->input('drop_database') == '1') {
            try {
                // DB::statement("DROP DATABASE IF EXISTS " . $dbName);
            } catch (\Exception $e) {
                return redirect()->route('dev.index')->with('warning', 'Project removed but DB delete failed: ' . $e->getMessage());
            }
        }

        return redirect()->route('dev.index')->with('success', 'Project deleted successfully!');
    }

    private function saveProjectsToConfig($projects)
    {
        $content = "<?php\nreturn [\n";
        foreach ($projects as $key => $project) {
            $content .= "    \"$key\" => [\n";
            // Preserve comments via static string if possible? No, we are rebuilding.
            if (isset($project['APP_KEY'])) {
                $content .= "        'APP_KEY' => '" . $project['APP_KEY'] . "',\n";
            }
            $content .= "        \"Prefix\" => \"" . ($project['Prefix'] ?? '') . "\",\n";
            $content .= "        'SEGMENT_NAME' => '" . ($project['SEGMENT_NAME'] ?? $key) . "',\n";
            $content .= "        \"DATABASE_NAME\" => \"" . ($project['DATABASE_NAME'] ?? '') . "\",\n";
            $content .= "        \"HOST\" => \"" . ($project['HOST'] ?? 'localhost') . "\",\n";
            $content .= "        \"USERNAME\" => \"" . ($project['USERNAME'] ?? 'root') . "\",\n";
            $content .= "        \"PASSWORD\" => \"" . ($project['PASSWORD'] ?? '') . "\"\n";
            $content .= "    ],\n";
        }
        $content .= "];\n";

        File::put(config_path('all_projects.php'), $content);
        Artisan::call('config:clear');
    }
}
